#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    eigakai-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^eigakai\.ddev\.site$`)
      
      service: "eigakai-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "eigakai-redirectHttps"
    eigakai-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^eigakai\.ddev\.site$`)
      
      service: "eigakai-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "eigakai-redirectHttps"
    
    
    
    eigakai-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^eigakai\.ddev\.site$`)
      
      service: "eigakai-web-80"
      ruleSyntax: v3
      
      tls: true
      
    eigakai-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^eigakai\.ddev\.site$`)
      
      service: "eigakai-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    eigakai-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    eigakai-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-eigakai-web:80
        
    eigakai-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-eigakai-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/eigakai.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/eigakai.key